version: "2"
services:
  pkg_sender:
    build: .
    container_name: pkg_sender
    volumes:
      - ./files:/mnt/192.168.10.10/data/Ps4-Mods/PS4
    ports:
      - 3333:8033
    environment:
      - PORT=8033
      - STATIC_FILES=/opt/apps/pkg_sender/files
      - LOCALIP=192.168.10.85
      - PS4IP=192.168.10.11
    restart: unless-stopped
